openapi: '3.0.2'
info:
  title: Dream Numeric Bank
  version: '1.0'
servers:
  - url: https://DNM.bank.server/v1
tags:
  - name: Account
  - name: Balance
  - name: TransactionCategory
  - name: TransferGroup
  - name: Transfer
  - name: Transaction
  - name: Debt
  - name: InterestRate

paths:
  /account:
    get:
      tags:
        - Account
      summary: Get all accounts
      description: The returned books are ordered by name.
      operationId: getAccounts
      responses:
        200:
          description: Successfully get all accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts'
        400:
          $ref: '#/components/responses/400'
        500:
          $ref: '#/components/responses/500'

    put:
      summary: Create or update accounts
      tags:
        - Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AccountComponent'
            example:
              - firstName: "Daww"
                lastName: "Face"
                birthDate: "2006-08-02"
                monthlySalary: 50000.0
                overDrafted: true

      responses:
        '200':
          description: Successfully created or updated accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountComponent'
              example:
                - idAccount: "siais-dadhad-dadjhadj-djqsd"
                  firstName: "Daww"
                  lastName: "Face"
                  birthDate: "2006-08-02T00:00:00Z"
                  monthlySalary: 50000.0
                  overDrafted: false
                  transactions: [ ]
                  balance: { }
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

  /account/{accountId}:
    get:
      summary: Retrieve an account by its ID
      operationId: getAccountById
      tags:
        - Account
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to retrieve
          example:
            - accountId: "siais-dadhad-dadjhadj-djqsd"
      responses:
        '200':
          description: Account retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts'
              example:
                - firstName: "Daww"
                  lastName: "Face"
                  birthDate: "2006-08-02"
                  monthlySalary: 50000.0
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    delete:
      summary: Delete an account
      tags:
        - Account
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts'
              example:
                - firstName: "Daww"
                  lastName: "Face"
                  birthDate: "2006-08-02"
                  monthlySalary: 50000.0
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

  /balance:
    get:
      summary: Retrieve all balances
      tags:
        - Balance
      responses:
        '200':
          description: Successfully got all balances
          content:
            application/json:
              schema:
                items:
                  - $ref: '#/components/schemas/balance'
                example:
                - balanceId: "fa5new-b4nce-id-784"
                  accountId: "uuua-65ada-ea45-aks"
                  currentBalance: 500.0

                - balanceId: "neadw-bdakd-id-745ad"
                  accountId: "adkd-adi5ad-adha-da"
                  currentBalance: 500.0

    put:
      summary: Create or update balances
      description: This endpoint is used to create or update existing balances. It accepts an array of balance details and updates the corresponding balances in the database.
      tags:
        - Balance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/balance'
            example:
              - amount: 1000.0
                balanceDatetime: "2023-04-01T10:00:00Z"
                idAccount: "siais-dadhad-dadjhadj-djqsd"
      responses:
        '200':
          description: Successfully created or updated balances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/balance'
              example:
                - amount: 1000.0
                  balanceDatetime: "2023-04-01T10:00:00Z"
                  idAccount: "siais-dadhad-dadjhadj-djqsd"
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

  /balance/{balanceId}:
    get:
      summary: Retrieve a balance by its ID
      operationId: getBalanceById
      tags:
        - Balance
      parameters:
        - in: path
          name: balanceId
          required: true
          schema:
            type: string
          description: The ID of the balance to retrieve
      responses:
        '200':
          description: Balance retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    delete:
      summary: Delete a balance
      tags:
        - Balance
      parameters:
        - in: path
          name: balanceId
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/schemas/balance'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /transaction-category:
    get:
      summary: Retrieve all transaction categories
      operationId: getAllTransactionCategories
      tags:
        - TransactionCategory
      responses:
        '200':
          description: List of transaction categories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionCategory'
        '500':
          $ref: '#/components/responses/500'

    put:
      summary: Create or update transaction categories
      operationId: saveOrUpdateTransactionCategory
      tags:
        - TransactionCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TransactionCategory'
      responses:
        '200':
          description: Transaction category created or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferCategory'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

  /transactioncategory/{transactionCategoryId}:
    get:
      summary: Retrieve a transaction category by its ID
      operationId: getTransactionCategoryById
      tags:
        - TransactionCategory
      parameters:
        - in: path
          name: transactionCategoryId
          required: true
          schema:
            type: string
          description: The ID of the transaction category to retrieve
      responses:
        '200':
          description: Transaction category retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCategory'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    delete:
      summary: Delete a transaction category by its ID
      operationId: deleteTransactionCategoryById
      tags:
        - TransactionCategory
      parameters:
        - in: path
          name: transactionCategoryId
          required: true
          schema:
            type: string
          description: The ID of the transaction category to delete
      responses:
        '200':
          description: Transaction category deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCategory'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /transfer-groups:
    put:
      summary: Create or update transfer groups
      operationId: createOrUpdateTransferGroup
      tags:
        - TransferGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferGroup'
      responses:
        '200':
          description: Transfer group created or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferGroup'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve all transfer groups
      operationId: getAllTransferGroups
      tags:
        - TransferGroup
      responses:
        '200':
          description: List of transfer groups retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferGroup'
        '500':
          $ref: '#/components/responses/500'

  /transfer-groups/{TransferGroupId}:
    delete:
      summary: Delete a transfer group by its ID
      operationId: deleteTransferGroupById
      tags:
        - TransferGroup
      parameters:
        - in: path
          name: TransferGroupId
          required: true
          schema:
            type: string
          description: The ID of the transfer group to delete
      responses:
        '200':
          description: Transfer group deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve a transfer group by its ID
      operationId: getTransferGroupById
      tags:
        - TransferGroup
      parameters:
        - in: path
          name: TransferGroupId
          required: true
          schema:
            type: string
          description: The ID of the transfer group to retrieve
      responses:
        '200':
          description: Transfer group retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferGroup'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /transfer:
    put:
      summary: Create or update transfers
      operationId: saveOrUpdateTransfer
      tags:
        - Transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Transfer saved or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve all transfers
      operationId: getAllTransfers
      tags:
        - Transfer
      responses:
        '200':
          description: List of transfers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
        '500':
          $ref: '#/components/responses/500'

  /transfer/{transferId}:
    delete:
      summary: Delete a transfer by its ID
      operationId: deleteTransferById
      tags:
        - Transfer
      parameters:
        - in: path
          name: transferId
          required: true
          schema:
            type: string
          description: The ID of the transfer to delete
      responses:
        '200':
          description: Transfer deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve a transfer by its ID
      operationId: getTransferById
      tags:
        - Transfer
      parameters:
        - in: path
          name: transferId
          required: true
          schema:
            type: string
          description: The ID of the transfer to retrieve
      responses:
        '200':
          description: Transfer retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /transaction:
    get:
      summary: Retrieve all transactions
      operationId: getAllTransactions
      tags:
        - Transaction
      responses:
        '200':
          description: List of transactions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '500':
          $ref: '#/components/responses/500'

    put:
      summary: Create or update transactions
      operationId: CreateOrUpdateTransaction
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transaction created or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /transaction/{transactionId}:
    get:
      summary: Retrieve a transaction by its ID
      operationId: getTransactionById
      tags:
        - Transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: The ID of the transaction to retrieve
      responses:
        '200':
          description: Transaction retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    delete:
      summary: Delete a transaction by its ID
      operationId: deleteTransactionById
      tags:
        - Transaction
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: string
          description: The ID of the transaction to delete
      responses:
        '200':
          description: Transaction deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /debt:
    get:
      summary: Retrieve all debts
      operationId: getAllDebts
      tags:
        - Debt
      responses:
        '200':
          description: List of debts retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/debt'
        '500':
          $ref: '#/components/responses/500'

  /debts/{debtId}:
    delete:
      summary: Delete a debt by its ID
      operationId: deleteDebtById
      tags:
        - Debt
      parameters:
        - in: path
          name: debtId
          required: true
          schema:
            type: string
          description: The ID of the debt to delete
      responses:
        '200':
          description: Debt deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /interest-rates:
    put:
      summary: Save or update interest rates
      operationId: saveOrUpdateInterestRate
      tags:
        - InterestRate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterestRate'
      responses:
        '200':
          description: Interest rate saved or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestRate'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve all interest rates
      operationId: getAllInterestRates
      tags:
        - InterestRate
      responses:
        '200':
          description: List of interest rates retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InterestRate'
        '500':
          $ref: '#/components/responses/500'

  /interest-rates/{InterestRate}:
    delete:
      summary: Delete an interest rate by its ID
      operationId: deleteInterestRateById
      tags:
        - InterestRate
      parameters:
        - in: path
          name: InterestRate
          required: true
          schema:
            type: string
          description: The ID of the interest rate to delete
      responses:
        '200':
          description: Interest rate deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestRate'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    get:
      summary: Retrieve an interest rate by its ID
      operationId: getInterestRateById
      tags:
        - InterestRate
      parameters:
        - in: path
          name: InterestRate
          required: true
          schema:
            type: string
          description: The ID of the interest rate to retrieve
      responses:
        '200':
          description: Interest rate retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestRate'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'

  schemas:
    #entity
    accounts:
      type: object
      properties:
        idAccount:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        monthlySalary:
          type: number
          format: double
        overDrafted:
          type: boolean

      example:
        - accountId: "siais-dadhad-dadjhadj-djqsd"
          firstName: "Daww"
          lastName: "Face"
          birthDate: "2006-08-02"
          monthlySalary: 50000.0
          balance: 2000.0
          debtList:
            [2000,4000,5000]
          overDrafted: false
        - accountId: "shasia-sasha-21sas-dadq"
          firstName: "All"
          lastName: "Smith"
          birthDate: "2005-05-14"
          balance: 2000.0
          debtList:
            [ 2000,4000,5000 ]
          monthlySalary: 6000000.0
          overDrafted: true

    AccountInput:
      type: object
      properties:
        idAccount:
          type: string
          description: The unique identifier of the account. If provided, this is an update; otherwise, it's a creation.
        firstName:
          type: string
          description: The first name of the account holder.
        lastName:
          type: string
          description: The last name of the account holder.
        birthDate:
          type: string
          format: date
          description: The birth date of the account holder.
        monthlySalary:
          type: number
          format: double
          description: The monthly salary of the account holder.
        overDrafted:
          type: boolean
          description: Indicates if the account is overdrafted.

    AccountComponent:
      type: object
      properties:
        idAccount:
          type: string
          description: The unique identifier of the account.
        firstName:
          type: string
          description: The first name of the account holder.
        lastName:
          type: string
          description: The last name of the account holder.
        birthDate:
          type: string
          format: date-time
          description: The birth date of the account holder.
        monthlySalary:
          type: number
          format: double
          description: The monthly salary of the account holder.
        overDrafted:
          type: boolean
          description: Indicates if the account is overdrafted.
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
          description: A list of transactions associated with the account.
        balance:
          $ref: '#/components/schemas/balance'
          description: The current balance of the account.

    balance:
      type: object
      properties:
        idBalance:
          type: string
          description: ID balance.
        amount:
          type: number
          format: double
          description: amount of the balance.
        balanceDatetime:
          type: string
          format: date-time
          description: The date and time of the balance.
        idAccount:
          type: string
          description: id account associated with this balance.
      required:
        - idAccount

    TransferCategory:
      type: object
      properties:
        idTransferCategory:
          type: string
          description: unique id.
        name:
          type: string
          description: The name of the transfer category.
        description:
          type: string
          description: The description of the transfer category.

    TransferGroup:
      type: object
      properties:
        idTransferGroup:
          type: string
          description: unique id of the transfer group.
        registrationDate:
          type: string
          format: date-time
          description: registration date of the transfer group.
        effectiveDate:
          type: string
          format: date-time
          description: effective date of the transfer group.
        idTransferCategory:
          type: string
          description: id of the transfer category associated with this transfer group.

    Transfer:
      type: object
      properties:
        idTransfer:
          type: string
          description: unique id of the transfer.
        reason:
          type: string
          description: The reason for the transfer.
        idTransferGroup:
          type: string
          description: The id of the transfer group associated with this transfer.
        transaction:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
      required:
        - reason
        - idTransferGroup

    Transaction:
      type: object
      properties:
        idTransaction:
          type: string
          description: The unique id of the transaction.
        transactionType:
          type: string
          enum:
            - EXPENSE
            - INCOME
          description: The type of the transaction.
        amount:
          type: number
          format: double
          description: The amount of the transaction.
        account:
          type: array
          items:
            $ref: '#/components/schemas/accounts'
          description: account associated with this transaction.
        transactionDateTime:
          type: string
          format: date-time
          description: The date and time of the transaction.
        reason:
          type: string
          description: reason of the transaction(description)
        transfer:
          type: array
          items:
            $ref: '#/components/schemas/Transfer'
        transactionCategory:
          type: array
          items:
            $ref: '#/components/schemas/TransactionCategory'

      required:
        - transactionType
        - amount
        - reason
        - transactionCategory

    TransactionCategory:
      type: object
      properties:
        idTransactionCategory:
          type: string
        name:
          type: string
        description:
          type: string

    InterestRate:
      type: object
      properties:
        idInterestRate:
          type: string
          description: id of the interest rate.
        value:
          type: number
          format: double
          description: The value of the interest rate.
        interestRateDatetime:
          type: string
          format: date-time
          description: The date and time when the interest rate was set.

    debt:
      type: object
      properties:
        idDebt:
          type: string
          description:  id of the debt.
        amount:
          type: number
          format: double
          description: The amount of the debt.
        debtDatetime:
          type: string
          format: date-time
          description: The date and time when the debt was incurred.
        idAccount:
          type: string
          description:  idaccount associated with this debt.
        idInterestRate:
          type: string
          description: idinterest rate associated with this debt.
      required:
        - amount
        - idAccount

    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
